function rep_Ger() {
document.body.innerHTML = document.body.innerHTML
.replaceAll("ATTENTION: Sale Ends Today", "ACHTUNG: Der Verkauf Endet Heute")
.replaceAll("Sunday", "Sonntag")
.replaceAll("Monday", "Montag")
.replaceAll("Tuesday", "Dienstag")
.replaceAll("Wednesday", "Mittwoch")
.replaceAll("Thursday", "Donnerstag")
.replaceAll("Friday", "Freitag")
.replaceAll("Saturday", "Samstag")
.replaceAll("January", "Januar")
.replaceAll("February", "Februar")
.replaceAll("March", "März")
.replaceAll("April", "April")
.replaceAll("May", "Mai")
.replaceAll("June", "Juni")
.replaceAll("July", "Juli")
.replaceAll("August", "August")
.replaceAll("September", "September")
.replaceAll("October", "Oktober")
.replaceAll("November", "November")
.replaceAll("December", "Dezember")
.replaceAll("Up to [DiscountValue] Discount", "Bis zu [DiscountValue] Rabatt")
.replaceAll("Sell Out Risk: <u>HIGH</u>", "Ausverkaufs Risiko: <u>HOHES</u>")
.replaceAll("Buy the official here", "Kaufen sie das offizielle hier")
.replaceAll("RUSH MY ORDER NOW", "JETZT KAUFEN")
.replaceAll("ORDER NOW", "JETZT KAUFEN")
.replaceAll("BUY THE OFFICIAL NOW", "KAUFEN SIE JETZT DAS OFFIZIELLE")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "ERHALTEN SIE DIE LETZTEN EINHEITEN")
.replaceAll("Hurry, you'll <u>lose</u> your discount in", "Beeilen sie sich, sie <u>verlieren</u> ihren rabatt in")
.replaceAll("Please, wait a few seconds for the page to load after clicking in the button", "Bitte warten sie einige sekunden, bis die seite geladen ist, nachdem sie auf die schaltfläche geklickt haben")
.replaceAll("Secure Payments", "Sichere Zahlungen")
.replaceAll("24/7 Dedicated", "24/7 Engagierte")
.replaceAll("Support", "Unterstützung")
.replaceAll("Save Up To <span style=\"color:#F19220;\">[DiscountValue]", "Sparen Sie Heute <span style=\"color:#F19220;\">[DiscountValue]")
.replaceAll("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "Die unglaubliche Formel von [ProductName] vereint hochwertige Rohstoffe aus verschiedenen Teilen der Welt, die in Synergie für maximale Leistung sorgen.")
.replaceAll("Save Up To <span style=\"color: #F19220;\">[DiscountValue]</span> Buying Now!", "Sparen Sie noch heute bis zu <span style=\"color: #F19220;\">[DiscountValue]</span>.")
.replaceAll("Natural Formula", "Natürliche Formel")
.replaceAll("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "Beanspruchen Sie Ihr Rabattiertes <span style=\"color: #F19220;\">[ProductName]</span> Unten Solange der Vorrat Reicht")
.replaceAll("Terms", "Allgemeine Geschäftsbedingungen")
.replaceAll("Privacy", "Datenschutz")
.replaceAll("Contact", "Kontakt")
.replaceAll("Shipping", "Versand")
.replaceAll("Disclaimer", "Haftungsausschluss")
.replaceAll("Order Now | All rights reserved", "Jetzt Kaufen | Alle rechte vorbehalten")
} rep_Ger();
