function rep_Ger() {
document.body.innerHTML = document.body.innerHTML
.replaceAll("ATTENTION: Sale Ends Today", "ACHTUNG: Der Verkauf Endet Heute")
.replaceAll("WARNING:</b></span> Due to extremely high media demand, there is limited supply of", "ACHTUNG:</b></span> aufgrund der extrem hohen mediennachfrage ist der vorrat an")
.replaceAll("in stock as of", "begrenzt ab dem")
.replaceAll("Sunday", "Sonntag")
.replaceAll("Monday", "Montag")
.replaceAll("Tuesday", "Dienstag")
.replaceAll("Wednesday", "Mittwoch")
.replaceAll("Thursday", "Donnerstag")
.replaceAll("Friday", "Freitag")
.replaceAll("Saturday", "Samstag")
.replaceAll("January", "Januar")
.replaceAll("February", "Februar")
.replaceAll("March", "März")
.replaceAll("April", "April")
.replaceAll("May", "Mai")
.replaceAll("June", "Juni")
.replaceAll("July", "Juli")
.replaceAll("August", "August")
.replaceAll("September", "September")
.replaceAll("October", "Oktober")
.replaceAll("November", "November")
.replaceAll("December", "Dezember")
.replaceAll("Up to [DiscountValue] Discount", "Bis zu [DiscountValue] Rabatt")
.replaceAll("Sell Out Risk", "Ausverkaufsrisiko")
.replaceAll("<u>HIGH</u>", "<u>HOCH</u>")
.replaceAll("Buy the official here", "Kaufen sie das offizielle hier")
.replaceAll("RUSH MY ORDER NOW", "JETZT KAUFEN")
.replaceAll("ORDER NOW", "JETZT KAUFEN")
.replaceAll("BUY THE OFFICIAL NOW", "KAUFEN SIE JETZT DAS OFFIZIELLE")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "ERHALTEN SIE DIE LETZTEN EINHEITEN")
.replaceAll("Hurry, you'll <u>lose</u> your discount in", "Beeilen sie sich, sie <u>verlieren</u> ihren rabatt in")
.replaceAll("Please, wait a few seconds for the page to load after clicking in the button", "Bitte warten sie einige sekunden, bis die seite geladen ist, nachdem sie auf die schaltfläche geklickt haben")
.replaceAll("Secure Payments", "Sichere Zahlungen")
.replaceAll("24/7 Dedicated", "24/7 Engagierte")
.replaceAll("Support", "Unterstützung")
.replaceAll("<span style=\"color:#F19220;\">[GuaranteeDays]</span> Day Guarantee", "<span style=\"color:#F19220;\">[GuaranteeDays]</span> Tage Garantie")
.replaceAll("Save Up To <span style=\"color:#F19220;\">[DiscountValue]", "Sparen Sie Heute <span style=\"color:#F19220;\">[DiscountValue]")
.replaceAll("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "Die unglaubliche Formel von [ProductName] vereint hochwertige Rohstoffe aus verschiedenen Teilen der Welt, die in Synergie für maximale Leistung sorgen.")
.replaceAll("Save Up To <span style=\"color: #F19220;\">[DiscountValue]</span> Buying Now!", "Sparen Sie noch heute bis zu <span style=\"color: #F19220;\">[DiscountValue]</span>.")
.replaceAll("Natural Formula", "Natürliche Formel")
.replaceAll("YOU’RE PROTECTED BY THE <span style=\"color: #F19220;\">[GuaranteeDays]-DAY MONEY BACK</span> GUARANTEE!", "SEI SIND DURCH DIE <span style=\"color: #F19220;\">[GuaranteeDays]-TAGE GELD-ZURÜCK</span> GARANTIE!")
.replaceAll("The sellers are so confident with [ProductName] and services, that they back it with a <b>[GuaranteeDays] day money back guarantee</b>.", "Die Verkäufer sind von [ProductName] und den Dienstleistungen so überzeugt, dass sie eine <b>[GuaranteeDays] Tagen Geld-zurück-Garantie gewähren</b>.")
.replaceAll("If for any reason you are not fully satisfied with their products, simply return the purchased products in the original container within [GuaranteeDays] days of when you received your order.", "Sollten Sie aus irgendeinem Grund mit den Produkten nicht vollständig zufrieden sein, senden Sie die gekauften Produkte einfach innerhalb von [GuaranteeDays] Tagen nach Erhalt Ihrer Bestellung in der Originalverpackung zurück.")
.replaceAll("They will refund you 100% of the purchase price, with absolutely no hassle.", "Sie erstatten Ihnen 100% des Kaufpreises, völlig unkompliziert.")
.replaceAll("BUY WITH GUARANTEE", "KAUFEN SIE MIT GARANTIE")
.replaceAll("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "Beanspruchen Sie Ihr Rabattiertes <span style=\"color: #F19220;\">[ProductName]</span> Unten Solange der Vorrat Reicht")
.replaceAll("MONEY BACK GUARANTEE !", "GELD-ZURÜCK-GARANTIE !")
.replaceAll("Terms", "Allgemeine Geschäftsbedingungen")
.replaceAll("Privacy", "Datenschutz")
.replaceAll("Contact", "Kontakt")
.replaceAll("Shipping", "Versand")
.replaceAll("Disclaimer", "Haftungsausschluss")
.replaceAll("Order Now | All rights reserved", "Jetzt Kaufen | Alle rechte vorbehalten")
} rep_Ger();
