var today = getNow.getDate() + ". " + getdayMonth[(getNow.getMonth())] + " " + thisYear + ".";
document.getElementById("today1").innerHTML = today;
document.body.innerHTML = document.body.innerHTML
.replaceAll("Warning:</span></b> Limited supply for", "Warnung:</span></b> Begrenzter Vorrat für")
.replaceAll("as of <b>", "ab <b>")
.replaceAll("Hurry!</b>", "Beeil dich!</b>")
.replace("January", "Januar")
.replace("February", "Februar")
.replace("March", "März")
.replace("April", "April")
.replace("May", "Mai")
.replace("June", "Juni")
.replace("July", "Juli")
.replace("August", "August")
.replace("September", "September")
.replace("October", "Oktober")
.replace("November", "November")
.replace("December", "Dezember")
.replaceAll("RUSH ORDER NOW", "JETZT BESTELLEN")
.replaceAll("RUSH MY ORDER", "JETZT KAUFEN")
.replaceAll("ORDER NOW", "JETZT KAUFEN")
.replace("<p>Try", "<p>Probieren Sie")
.replace("Up to <b><u>[DiscValue]</u></b> OFF Today!", "Bis zu <b><u>[DiscValue]</u></b> OFF Heute!")
.replace("Free Shipping on <b><u>Every Order!", "Kostenloser Versand für <b><u>Jede Bestellung!")
.replaceAll("Available to", "Nur für")
.replaceAll("[Country] only", "[Country] verfügbar")
.replace("100% Satisfaction", "100% Zufriedenheit")
.replace("[GuaDays]-Day Money Back Guarantee", "[GuaDays] Tage Geld-Zurück-Garantie")
.replace("comes with a 100% money back guarantee", "bietet eine 100% Geld-zurück-Garantie")
.replace("full days from your original purchase. If you’re not totally and completely satisfied with their product or your results within the first [GuaDays] days simply let the vendors know by calling their toll-free number or dropping them an email and they’ll gladly give you a full refund within 48 hours of the product being returned. That’s right", "volle Tage ab Ihrem ursprünglichen Kauf. Wenn Sie innerhalb der ersten [GuaDays]-Tage nicht vollständig mit dem Produkt oder Ihren Ergebnissen zufrieden sind, teilen Sie dies einfach den Anbietern mit, indem Sie ihre gebührenfreie Nummer anrufen oder ihnen eine E-Mail schreiben. Sie erhalten dann gerne innerhalb weniger Tage eine volle Rückerstattung 48 Stunden nach Rückgabe des Produkts. Das ist richtig")
.replace("simply return the product, even your empty bottles, anytime within [GuaDays] days of your purchase and you’ll receive a full, no-questions-asked refund (minus shipping and handling fees)", "Geben Sie das Produkt einfach jederzeit innerhalb von [GuaDays] Tagen nach dem Kauf zurück, auch Ihre leeren Flaschen, und Sie erhalten eine vollständige Rückerstattung ohne weitere Fragen (abzüglich Versand- und Bearbeitungsgebühren)")
.replace("Inside every", "In jeder")
.replace("you’ll find", "du wirst es finden")
.replace("Natural Formula", "Natürliche Formel")
.replace("Easy to Use", "Einfach zu verwenden")
.replace("Non-GMO", "GVO-frei")
.replace("No Stimulants", "Keine Stimulanzien")
.replace("Non-Habit Forming", "Keine Gewohnheitsbildung")
.replace("Gluten Free", "Glutenfrei")
.replace("Order <b>[MaxUnits] Bottles</b> or <b>[MidUnits] Bottles</b> and Get <b><u>2 FREE Bonuses", "Bestellen Sie <b>[MaxUnits] Flaschen</b> oder <b>[MidUnits] Flaschen</b> und erhalten Sie <b><u>2 KOSTENLOSE Boni")
.replace("Every Order Comes With", "Bei jeder Bestellung ist der")
.replace("FREE Shipping</u> Too", "Versand KOSTENLOS</u>")
.replace("97% Of Customers Order [MaxUnits] Bottles (The Recommended Option)", "97% der Kunden Bestellen [MaxUnits]-Flaschen (Die Empfohlene Option)")
.replace("Real […] Users", "Echte […] Benutzer")
.replace("Real Life-Changing Results", "Ergebnisse, Die Das Leben Verändern")
.replaceAll("Verified Purchase", "Verifizierter Kauf")
.replace("Frequently Asked Questions", "Häufig Gestellte Fragen")
.replace("Claim Your Discounted […] Below While Stocks Last", "Fordern Sie Unten Ihren Ermäßigten […] an, solange der Vorrat Reicht")
.replace("Customers say", "Kunden sagen")
.replace("based on", "basierend auf")
.replace("reviews!", "Bewertungen!")
.replace("Scientific References", "Wissenschaftliche Referenzen")
.replace("Please note that the information we provide is not intended to replace consultation with a qualified medical professional. We encourage you to inform your physician of changes you make to your lifestyle and discuss these with him or her. For questions or concerns about any medical conditions you may have, please contact your doctor.", "Bitte beachten Sie, dass die von uns bereitgestellten Informationen nicht dazu gedacht sind, die Konsultation eines qualifizierten Arztes zu ersetzen. Wir empfehlen Ihnen, Ihren Arzt über Änderungen Ihres Lebensstils zu informieren und diese mit ihm zu besprechen. Bei Fragen oder Bedenken zu eventuellen Erkrankungen wenden Sie sich bitte an Ihren Arzt.")
.replace("Statements on this website have not been evaluated by the Food and Drug Administration. Products are not intended to diagnose, treat, cure or prevent any disease. If you are pregnant, nursing, taking medication, or have a medical condition, consult your physician before using these products.", "Die Aussagen auf dieser Website wurden nicht von der Food and Drug Administration geprüft. Die Produkte sind nicht dazu bestimmt, Krankheiten zu diagnostizieren, zu behandeln, zu heilen oder zu verhindern. Wenn Sie schwanger sind, stillen, Medikamente einnehmen oder an einer Krankheit leiden, konsultieren Sie Ihren Arzt, bevor Sie diese Produkte verwenden.")
.replace("Results in description and testimonials may not be typical results and individual results may vary.", "Die Ergebnisse in Beschreibungen und Erfahrungsberichten sind möglicherweise keine typischen Ergebnisse und die einzelnen Ergebnisse können variieren.")
.replace("Terms", "Allgemeine Geschäftsbedingungen")
.replace("Privacy", "Datenschutz")
.replace("Contact", "Kontakt")
.replace("References", "Verweise")
.replace("Return", "Rückgaberecht")
.replace("Shipping", "Versand")
.replace("Disclaimer", "Haftungsausschluss")
.replace("Report Spam", "Spam Melden")
.replace("Order Now. All Rights Reserved.", "Jetzt Kaufen. Alle Rechte vorbehalten.")
