function rep_Swe() {
document.body.innerHTML = document.body.innerHTM
.replaceAll("ATTENTION: Sale Ends Today", "UPPMARKSAMHET: Rean Slutar Idag")
.replaceAll("Sunday", "sondag")
.replaceAll("Monday", "mandag")
.replaceAll("Tuesday", "tisdag")
.replaceAll("Wednesday", "onsdag")
.replaceAll("Thursday", "torsdag")
.replaceAll("Friday", "fredag")
.replaceAll("Saturday", "lordag")
.replaceAll("January", "januari")
.replaceAll("February", "februari")
.replaceAll("March", "mars")
.replaceAll("April", "april")
.replaceAll("May", "maj")
.replaceAll("June", "juni")
.replaceAll("July", "juli")
.replaceAll("August", "augusti")
.replaceAll("September", "september")
.replaceAll("October", "oktober")
.replaceAll("November", "november")
.replaceAll("December", "december")
.replaceAll("Up to [DiscountValue] Discount", "Upp Till [DiscountValue] Rabatt")
.replaceAll("Sell Out Risk: <u>HIGH</u>", "SAlja Ut Risk: <u>HoG</u>")
.replaceAll("Buy the official here", "Kop den officiella hAr")
.replaceAll("RUSH MY ORDER NOW", "BESTALL NU")
.replaceAll("ORDER NOW", "BESTALL NU")
.replaceAll("BUY THE OFFICIAL NOW", "KoP DEN OFFICIELLA NU")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "Fa SISTA ENHETER MED RABATT")
.replaceAll("Hurry, you'll <u>lose</u> your discount in", "Skynda dig, du <u>forlorar</u> din rabatt pa")
.replaceAll("Please, wait a few seconds for the page to load after clicking in the button", "Vanta nagra sekunder tills sidan laddas efter att du har klickat pa knappen")
.replaceAll("Secure Payments", "SAkra Betalningar")
.replaceAll("24/7 Dedicated", "24/7 Dedikerat")
.replaceAll("Support", "Stod")
.replaceAll("<span style=\"color:#F19220;\">[GuaranteeDays]</span> Day Guarantee", "<span style=\"color:#F19220;\">[GuaranteeDays]</span> Dagars Garanti")
.replaceAll("Save Up To <span style=\"color:#F19220;\">[DiscountValue]", "Spara Upp Till <span style=\"color:#F19220;\">[DiscountValue]")
.replaceAll("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "[ProductName] otroliga formel forenar hogkvalitativa ravaror fran olika delar av vArlden som fungerar i synergi for maximal prestanda.")
.replaceAll("Save Up To <span style=\"color: #F19220;\">[DiscountValue]</span> Buying Now!", "Spara Upp Till <span style=\"color: #F19220;\">[DiscountValue]</span> Genom att Kopa det Nu!")
.replaceAll("Natural Formula", "Naturlig Formel")
.replaceAll("YOU’RE PROTECTED BY THE <span style=\"color: #F19220;\">[GuaranteeDays]-DAY MONEY BACK</span> GUARANTEE!", "DU SKYDDAS AV <span style=\"color: #F19220;\">[GuaranteeDays] DAGARS PENGAR TILLBAKA</span> GARANTI!")
.replaceAll("The sellers are so confident with [ProductName] and services, that they back it with a <b>[GuaranteeDays] day money back guarantee</b>.", "SAljarna Ar sa overtygade om [ProductName] och tjAnsterna, Att de backar upp det med en <b>[GuaranteeDays] dagars pengarna-tillbaka-garanti</b>.")
.replaceAll("If for any reason you are not fully satisfied with their products, simply return the purchased products in the original container within [GuaranteeDays] days of when you received your order.", "Om du av nagon anledning inte Ar helt nojd med deras produkter, returnera helt enkelt de kopta produkterna i originalforpackningen inom [GuaranteeDays] dagar fran det att du mottog din bestAllning.")
.replaceAll("They will refund you 100% of the purchase price, with absolutely no hassle.", "De kommer att aterbetala dig 100% av inkopspriset, helt utan krangel.")
.replaceAll("BUY WITH GUARANTEE", "KoP MED GARANTI")
.replaceAll("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "HAmta Din Rabatterade <span style=\"color: #F19220;\">[ProductName]</span> Nedan sa LAnge Lagret RAcker")
.replaceAll("Terms", "AnvAndarvillkor")
.replaceAll("Privacy", "Integritetspolicy")
.replaceAll("Contact", "Kontakta Oss")
.replaceAll("Shipping", "Fraktpolicy")
.replaceAll("Disclaimer", "Varning")
.replaceAll("Order Now | All rights reserved", "BestAll Nu | Alla rAttigheter forbehallna")
} rep_Swe();
