function rep_Swe() {
document.body.innerHTML = document.body.innerHTML
.replaceAll("ATTENTION: Sale Ends Today", "UPPMÄRKSAMHET: Rean Slutar Idag")
.replaceAll("WARNING:</b></span> Due to extremely high media demand, there is limited supply of", "VARNING:</b></span> På grund av extremt hög medieefterfrågan, finns det ett begränsat utbud av")
.replaceAll("in stock as of", "i lager från och med den")
.replaceAll("Sunday", "söndag")
.replaceAll("Monday", "måndag")
.replaceAll("Tuesday", "tisdag")
.replaceAll("Wednesday", "onsdag")
.replaceAll("Thursday", "torsdag")
.replaceAll("Friday", "fredag")
.replaceAll("Saturday", "lördag")
.replaceAll("January", "januari")
.replaceAll("February", "februari")
.replaceAll("March", "mars")
.replaceAll("April", "april")
.replaceAll("May", "maj")
.replaceAll("June", "juni")
.replaceAll("July", "juli")
.replaceAll("August", "augusti")
.replaceAll("September", "september")
.replaceAll("October", "oktober")
.replaceAll("November", "november")
.replaceAll("December", "december")
.replaceAll("Sell Out Risk: <u>HIGH</u>", "Sälja Ut Risk: <u>HÖG</u>")
.replaceAll("Buy the official here", "Köp den officiella här")
.replaceAll("RUSH MY ORDER NOW", "BESTÄLL NU")
.replaceAll("ORDER NOW", "BESTÄLL NU")
.replaceAll("BUY THE OFFICIAL NOW", "KÖP DEN OFFICIELLA NU")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "FÅ SISTA ENHETER MED RABATT")
.replaceAll("Hurry, you'll <u>lose</u> your discount in", "Skynda dig, du <u>förlorar</u> din rabatt på")
.replaceAll("Please, wait a few seconds for the page to load after clicking in the button", "Vänta några sekunder tills sidan laddas efter att du har klickat på knappen")
.replaceAll("Secure Payments", "Säkra Betalningar")
.replaceAll("24/7 Dedicated", "24/7 Dedikerat")
.replaceAll("Support", "Stöd")
.replaceAll("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "[ProductName] otroliga formel förenar högkvalitativa råvaror från olika delar av världen som fungerar i synergi för maximal prestanda.")
.replaceAll("Natural Formula", "Naturlig Formel")
.replaceAll("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "Hämta Din Rabatterade <span style=\"color: #F19220;\">[ProductName]</span> Nedan så Länge Lagret Räcker")
.replaceAll("Terms", "Användarvillkor")
.replaceAll("Privacy", "Integritetspolicy")
.replaceAll("Contact", "Kontakta Oss")
.replaceAll("Shipping", "Fraktpolicy")
.replaceAll("Disclaimer", "Varning")
.replaceAll("Order Now | All rights reserved", "Beställ Nu | Alla rättigheter förbehållna")
} rep_Swe();
