function rep_Swe() {
.replaceAll("ATTENTION: Sale Ends Today", "UPPMÄRKSAMHET: Rean Slutar Idag")
.replaceAll("Sunday", "söndag")
.replaceAll("Monday", "måndag")
.replaceAll("Tuesday", "tisdag")
.replaceAll("Wednesday", "onsdag")
.replaceAll("Thursday", "torsdag")
.replaceAll("Friday", "fredag")
.replaceAll("Saturday", "lördag")
.replaceAll("January", "januari")
.replaceAll("February", "februari")
.replaceAll("March", "mars")
.replaceAll("April", "april")
.replaceAll("May", "maj")
.replaceAll("June", "juni")
.replaceAll("July", "juli")
.replaceAll("August", "augusti")
.replaceAll("September", "september")
.replaceAll("October", "oktober")
.replaceAll("November", "november")
.replaceAll("December", "december")
} rep_Swe();
