function rep_Swe() {
document.body.innerHTML = document.body.innerHTML
.replaceAll("ATTENTION: Sale Ends Today", "UPPMÄRKSAMHET: Rean Slutar Idag")
.replaceAll("WARNING:</b></span> Due to extremely high media demand, there is limited supply of", "VARNING:</b></span> På grund av extremt hög medieefterfrågan, finns det ett begränsat utbud av")
.replaceAll("in stock as of", "i lager från och med den")
.replaceAll("Sunday", "söndag")
.replaceAll("Monday", "måndag")
.replaceAll("Tuesday", "tisdag")
.replaceAll("Wednesday", "onsdag")
.replaceAll("Thursday", "torsdag")
.replaceAll("Friday", "fredag")
.replaceAll("Saturday", "lördag")
.replaceAll("January", "januari")
.replaceAll("February", "februari")
.replaceAll("March", "mars")
.replaceAll("April", "april")
.replaceAll("May", "maj")
.replaceAll("June", "juni")
.replaceAll("July", "juli")
.replaceAll("August", "augusti")
.replaceAll("September", "september")
.replaceAll("October", "oktober")
.replaceAll("November", "november")
.replaceAll("December", "december")
.replaceAll("Sell Out Risk: <u>HIGH</u>", "Sälja Ut Risk: <u>HÖG</u>")
.replaceAll("Buy the official here", "Köp den officiella här")
.replaceAll("RUSH MY ORDER NOW", "BESTÄLL NU")
.replaceAll("ORDER NOW", "BESTÄLL NU")
.replaceAll("BUY THE OFFICIAL NOW", "KÖP DEN OFFICIELLA NU")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "FÅ SISTA ENHETER MED RABATT")
.replaceAll("Hurry, you'll <u>lose</u> your discount in", "Skynda dig, du <u>förlorar</u> din rabatt på")
.replaceAll("Please, wait a few seconds for the page to load after clicking in the button", "Vänta några sekunder tills sidan laddas efter att du har klickat på knappen")
.replaceAll("Secure Payments", "Säkra Betalningar")
.replaceAll("24/7 Dedicated", "24/7 Dedikerat")
.replaceAll("Support", "Stöd")
.replaceAll("<span style=\"color:#F19220;\">[GuaranteeDays]</span> Day Guarantee", "<span style=\"color:#F19220;\">[GuaranteeDays]</span> Dagars Garanti")
.replaceAll("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "[ProductName] otroliga formel förenar högkvalitativa råvaror från olika delar av världen som fungerar i synergi för maximal prestanda.")
.replaceAll("Natural Formula", "Naturlig Formel")
.replaceAll("YOU’RE PROTECTED BY THE <span style=\"color: #F19220;\">[GuaranteeDays]-DAY MONEY BACK</span> GUARANTEE!", "DU SKYDDAS AV <span style=\"color: #F19220;\">[GuaranteeDays] DAGARS PENGAR TILLBAKA</span> GARANTI!")
.replaceAll("The sellers are so confident with [ProductName] and services, that they back it with a <b>[GuaranteeDays] day money back guarantee</b>.", "Säljarna är så övertygade om [ProductName] och tjänsterna, Att de backar upp det med en <b>[GuaranteeDays] dagars pengarna-tillbaka-garanti</b>.")
.replaceAll("If for any reason you are not fully satisfied with their products, simply return the purchased products in the original container within [GuaranteeDays] days of when you received your order.", "Om du av någon anledning inte är helt nöjd med deras produkter, returnera helt enkelt de köpta produkterna i originalförpackningen inom [GuaranteeDays] dagar från det att du mottog din beställning.")
.replaceAll("They will refund you 100% of the purchase price, with absolutely no hassle.", "De kommer att återbetala dig 100% av inköpspriset, helt utan krångel.")
.replaceAll("BUY WITH GUARANTEE", "KÖP MED GARANTI")
.replaceAll("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "Hämta Din Rabatterade <span style=\"color: #F19220;\">[ProductName]</span> Nedan så Länge Lagret Räcker")
.replaceAll("MONEY BACK GUARANTEE !", "PENGAR TILLBAKA GARANTI !")
.replaceAll("Terms", "Användarvillkor")
.replaceAll("Privacy", "Integritetspolicy")
.replaceAll("Contact", "Kontakta Oss")
.replaceAll("Shipping", "Fraktpolicy")
.replaceAll("Disclaimer", "Varning")
.replaceAll("Order Now | All rights reserved", "Beställ Nu | Alla rättigheter förbehållna")
} rep_Swe();
