function rep_Nor() {
document.body.innerHTML = document.body.innerHTML
.replaceAll("ATTENTION: Sale Ends Today", "OPPMERKSOMHET: Salg Slutter i Dag")
.replaceAll("Sunday", "søndag")
.replaceAll("Monday", "mandag")
.replaceAll("Tuesday", "tirsdag")
.replaceAll("Wednesday", "onsdag")
.replaceAll("Thursday", "torsdag")
.replaceAll("Friday", "fredag")
.replaceAll("Saturday", "lørdag")
.replaceAll("January", "januar")
.replaceAll("February", "februar")
.replaceAll("March", "mars")
.replaceAll("April", "april")
.replaceAll("May", "mai")
.replaceAll("June", "juni")
.replaceAll("July", "juli")
.replaceAll("August", "august")
.replaceAll("September", "september")
.replaceAll("October", "oktober")
.replaceAll("November", "november")
.replaceAll("December", "desember")
.replaceAll("Sell Out Risk: <u>HIGH</u>", "Selg Ut Risiko: <u>HØY</u>")
.replaceAll("Buy the official here", "Kjøp det offisielle her")
.replaceAll("RUSH MY ORDER NOW", "BESTILL RASK")
.replaceAll("ORDER NOW", "BESTILL NÅ")
.replaceAll("BUY THE OFFICIAL NOW", "KJØP DET OFFISIELLE NÅ")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "FÅ SISTE ENHETER MED RABATT")
.replaceAll("Hurry, you'll <u>lose</u> your discount in", "Skynd deg, du mister rabatten din på")
.replaceAll("Please, wait a few seconds for the page to load after clicking in the button", "Vennligst, vent noen sekunder til siden lastes inn etter at du har klikket på knappen")
.replaceAll("Secure Payments", "Sikre Betalinger")
.replaceAll("24/7 Dedicated", "24/7 Dedikert")
.replaceAll("Support", "Støtte")
.replaceAll("<span style=\"color:#F19220;\">[GuaranteeDays]</span> Day Guarantee", "<span style=\"color:#F19220;\">[GuaranteeDays]</span> Dagers Garanti")
.replaceAll("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "[ProductName] utrolige formel samler råvarer av høy kvalitet hentet fra forskjellige deler av verden som fungerer i synergi for maksimal ytelse.")
.replaceAll("Natural Formula", "Naturlig Formel")
.replaceAll("YOU’RE PROTECTED BY THE <span style=\"color: #F19220;\">[GuaranteeDays]-DAY MONEY BACK</span> GUARANTEE!", "DU ER BESKYTTET AV <span style=\"color: #F19220;\">[GuaranteeDays]-DAGERS PENGE-TILBAKE</span>-GARANTI!")
.replaceAll("The sellers are so confident with [ProductName] and services, that they back it with a <b>[GuaranteeDays] day money back guarantee</b>.", "Selgerne er så sikre på [ProductName] og tjenestene at de støtter det med en <b>[GuaranteeDays] dagers pengene-tilbake-garanti</b>.")
.replaceAll("If for any reason you are not fully satisfied with their products, simply return the purchased products in the original container within [GuaranteeDays] days of when you received your order.", "Hvis du av en eller annen grunn ikke er helt fornøyd med produktene deres, returnerer du ganske enkelt de kjøpte produktene i originalbeholderen innen [GuaranteeDays] dager etter at du mottok bestillingen.")
.replaceAll("They will refund you 100% of the purchase price, with absolutely no hassle.", "De vil refundere deg 100% av kjøpesummen, helt uten problemer.")
.replaceAll("BUY WITH GUARANTEE", "KJØP MED GARANTI")
.replaceAll("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "Gjør Krav på Det Rabatterte <span style=\"color: #F19220;\">[ProductName]</span> Ditt Nedenfor så Lenge Beholdningen Rekker")
.replaceAll("Terms", "Vilkår")
.replaceAll("Privacy", "Personvernerklæring")
.replaceAll("Contact", "Kontakt Oss")
.replaceAll("Shipping", "Frakt")
.replaceAll("Disclaimer", "Ansvarsfraskrivelse")
.replaceAll("Order Now | All rights reserved", "Bestill Nå | Alle rettigheter forbeholdt")
} rep_Nor();
