function rep_Nor() {
document.body.innerHTML = document.body.innerHTML
.replaceAll("ATTENTION: Sale Ends Today", "OPPMERKSOMHET: Salg Slutter i Dag")
.replaceAll("WARNING:</b></span> Due to extremely high media demand, there is limited supply of", "ADVARSEL:</b></span> På grunn av ekstremt høy medieetterspørsel, er det begrenset tilgang på")
.replaceAll("in stock as of", "på lager fra og med")
.replaceAll("Sunday", "søndag")
.replaceAll("Monday", "mandag")
.replaceAll("Tuesday", "tirsdag")
.replaceAll("Wednesday", "onsdag")
.replaceAll("Thursday", "torsdag")
.replaceAll("Friday", "fredag")
.replaceAll("Saturday", "lørdag")
.replaceAll("January", "januar")
.replaceAll("February", "februar")
.replaceAll("March", "mars")
.replaceAll("April", "april")
.replaceAll("May", "mai")
.replaceAll("June", "juni")
.replaceAll("July", "juli")
.replaceAll("August", "august")
.replaceAll("September", "september")
.replaceAll("October", "oktober")
.replaceAll("November", "november")
.replaceAll("December", "desember")
.replaceAll("Up to [DiscountValue] Discount", "Opptil [DiscountValue] Rabatt")
.replaceAll("Sell Out Risk: <u>HIGH</u>", "Selg Ut Risiko: <u>HØY</u>")
.replaceAll("Buy the official here", "Kjøp det offisielle her")
.replaceAll("RUSH MY ORDER NOW", "BESTILL RASK")
.replaceAll("ORDER NOW", "BESTILL NÅ")
.replaceAll("BUY THE OFFICIAL NOW", "KJØP DET OFFISIELLE NÅ")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "FÅ SISTE ENHETER MED RABATT")
.replaceAll("Hurry, you'll <u>lose</u> your discount in", "Skynd deg, du <u>mister</u> rabatten din på")
.replaceAll("Please, wait a few seconds for the page to load after clicking in the button", "Vennligst, vent noen sekunder til siden lastes inn etter at du har klikket på knappen")
.replaceAll("Secure Payments", "Sikre Betalinger")
.replaceAll("24/7 Dedicated", "24/7 Dedikert")
.replaceAll("Support", "Støtte")
.replaceAll("Save Up To <span style=\"color:#F19220;\">[DiscountValue]", "Spar Opptil <span style=\"color:#F19220;\">[DiscountValue]")
.replaceAll("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "[ProductName] utrolige formel samler råvarer av høy kvalitet hentet fra forskjellige deler av verden som fungerer i synergi for maksimal ytelse.")
.replaceAll("Save Up To <span style=\"color: #F19220;\">[DiscountValue]</span> Buying Now!", "Spar Opptil <span style=\"color: #F19220;\">[DiscountValue]</span> Ved å Kjøpe Nå!")
.replaceAll("Natural Formula", "Naturlig Formel")
.replaceAll("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "Gjør Krav på Det Rabatterte <span style=\"color: #F19220;\">[ProductName]</span> Ditt Nedenfor så Lenge Beholdningen Rekker")
.replaceAll("Terms", "Vilkår")
.replaceAll("Privacy", "Personvernerklæring")
.replaceAll("Contact", "Kontakt Oss")
.replaceAll("Shipping", "Frakt")
.replaceAll("Disclaimer", "Ansvarsfraskrivelse")
.replaceAll("Order Now | All rights reserved", "Bestill Nå | Alle rettigheter forbeholdt")
} rep_Nor();
