function rep_Ita() {
document.body.innerHTML = document.body.innerHTML
.replaceAll("ATTENTION: Sale Ends Today", "ATTENZIONE: La Vendita Termina Oggi")
.replaceAll("Sunday", "domenica")
.replaceAll("Monday", "lunedì")
.replaceAll("Tuesday", "martedì")
.replaceAll("Wednesday", "mercoledì")
.replaceAll("Thursday", "giovedì")
.replaceAll("Friday", "venerdì")
.replaceAll("Saturday", "sabato")
.replaceAll("January", "gennaio")
.replaceAll("February", "febbraio")
.replaceAll("March", "marzo")
.replaceAll("April", "aprile")
.replaceAll("May", "maggio")
.replaceAll("June", "giugno")
.replaceAll("July", "luglio")
.replaceAll("August", "agosto")
.replaceAll("September", "settembre")
.replaceAll("October", "ottobre")
.replaceAll("November", "novembre")
.replaceAll("December", "dicembre")
.replaceAll("Sell Out Risk: <u>HIGH</u>", "Rischio di Svendita: <u>ALTO</u>")
.replaceAll("Buy the official here", "Acquista il ufficiale qui")
.replaceAll("RUSH MY ORDER NOW", "ORDINA ORA")
.replaceAll("ORDER NOW", "ORDINA ORA")
.replaceAll("BUY THE OFFICIAL NOW", "COMPRA IL UFFICIALE ORA!")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "OTTIENI LE ULTIME UNITÀ CON SCONTO")
.replaceAll("Hurry, you'll <u>lose</u> your discount in", "Sbrigati, <u>perderai</u> lo sconto tra")
.replaceAll("Please, wait a few seconds for the page to load after clicking in the button", "Per favore, attendi qualche secondo affinché la pagina si carichi dopo aver cliccato sul pulsante")
.replaceAll("Secure Payments", "Pagamenti Sicuri")
.replaceAll("24/7 Dedicated", "24/7 Supporto")
.replaceAll("Support", "Dedicato")
.replaceAll("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "L'incredibile formula di [ProductName] riunisce ingredienti grezzi di alta qualità provenienti da diverse parti del mondo che lavorano in sinergia per le massime prestazioni.")
.replaceAll("Natural Formula", "Formula Naturale")
.replaceAll("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "Richiedi il tuo <span style=\"color: #F19220;\">[ProductName]</span> Scontato di Seguito Fino a Esaurimento Scorte")
.replaceAll("Terms", "Termini")
.replaceAll("Privacy", "Privacy")
.replaceAll("Contact", "Contatto")
.replaceAll("Shipping", "Spedizione")
.replaceAll("Disclaimer", "Disclaimer")
.replaceAll("Order Now | All rights reserved", "Ordina Ora | Tutti i diritti riservati")
} rep_Ita();
