function rep_Ita() {
document.body.innerHTML = document.body.innerHTML
.replaceAll("ATTENTION: Sale Ends Today", "ATTENZIONE: La Vendita Termina Oggi")
.replaceAll("Sunday", "domenica")
.replaceAll("Monday", "lunedì")
.replaceAll("Tuesday", "martedì")
.replaceAll("Wednesday", "mercoledì")
.replaceAll("Thursday", "giovedì")
.replaceAll("Friday", "venerdì")
.replaceAll("Saturday", "sabato")
.replaceAll("January", "gennaio")
.replaceAll("February", "febbraio")
.replaceAll("March", "marzo")
.replaceAll("April", "aprile")
.replaceAll("May", "maggio")
.replaceAll("June", "giugno")
.replaceAll("July", "luglio")
.replaceAll("August", "agosto")
.replaceAll("September", "settembre")
.replaceAll("October", "ottobre")
.replaceAll("November", "novembre")
.replaceAll("December", "dicembre")
.replaceAll("Sell Out Risk: <u>HIGH</u>", "Rischio di Svendita: <u>ALTO</u>")
.replaceAll("Buy the official here", "Acquista il ufficiale qui")
.replaceAll("RUSH MY ORDER NOW", "ORDINA ORA")
.replaceAll("ORDER NOW", "ORDINA ORA")
.replaceAll("BUY THE OFFICIAL NOW", "COMPRA IL UFFICIALE ORA!")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "OTTIENI LE ULTIME UNITÀ CON SCONTO")
.replaceAll("Hurry, you'll <u>lose</u> your discount in", "Sbrigati, <u>perderai</u> lo sconto tra")
.replaceAll("Please, wait a few seconds for the page to load after clicking in the button", "Per favore, attendi qualche secondo affinché la pagina si carichi dopo aver cliccato sul pulsante")
.replaceAll("Secure Payments", "Pagamenti Sicuri")
.replaceAll("24/7 Dedicated", "24/7 Supporto")
.replaceAll("Support", "Dedicato")
.replaceAll("<span style=\"color:#F19220;\">[GuaranteeDays]</span> Day Guarantee", "Garanzia di <span style=\"color:#F19220;\">[GuaranteeDays]</span> Giorni")
.replaceAll("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "L'incredibile formula di [ProductName] riunisce ingredienti grezzi di alta qualità provenienti da diverse parti del mondo che lavorano in sinergia per le massime prestazioni.")
.replaceAll("Natural Formula", "Formula Naturale")
.replaceAll("YOU’RE PROTECTED BY THE <span style=\"color: #F19220;\">[GuaranteeDays]-DAY MONEY BACK</span> GUARANTEE!", "SEI PROTETTO DALLA <span style=\"color: #F19220;\">GARANZIA DI [GuaranteeDays]</span> GIORNI!")
.replaceAll("The sellers are so confident with [ProductName] and services, that they back it with a <b>[GuaranteeDays] day money back guarantee</b>.", "I venditori sono così sicuri di [ProductName] e dei servizi che lo supportano con una <b>garanzia di [GuaranteeDays] giorni</b>.")
.replaceAll("If for any reason you are not fully satisfied with their products, simply return the purchased products in the original container within [GuaranteeDays] days of when you received your order.", "Se per qualsiasi motivo non sei completamente soddisfatto dei loro prodotti, è sufficiente restituire i prodotti acquistati nella confezione originale entro [GuaranteeDays] giorni da quando hai ricevuto l'ordine.")
.replaceAll("They will refund you 100% of the purchase price, with absolutely no hassle.", "Ti rimborseranno il 100% del prezzo di acquisto, senza alcun problema.")
.replaceAll("BUY WITH GUARANTEE", "ORDINA CON GARANZIA")
.replaceAll("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "Richiedi il tuo <span style=\"color: #F19220;\">[ProductName]</span> Scontato di Seguito Fino a Esaurimento Scorte")
.replaceAll("Terms", "Termini")
.replaceAll("Privacy", "Privacy")
.replaceAll("Contact", "Contatto")
.replaceAll("Shipping", "Spedizione")
.replaceAll("Disclaimer", "Disclaimer")
.replaceAll("Order Now | All rights reserved", "Ordina Ora | Tutti i diritti riservati")
} rep_Ita();
