function rep_Nld() {
.replaceAll("ATTENTION: Sale Ends Today", "AANDACHT: Verkoop Eindigt Vandaag")
.replaceAll("Sunday", "zondag")
.replaceAll("Monday", "maandag")
.replaceAll("Tuesday", "dinsdag")
.replaceAll("Wednesday", "woensdag")
.replaceAll("Thursday", "donderdag")
.replaceAll("Friday", "vrijdag")
.replaceAll("Saturday", "zaterdag")
.replaceAll("January", "januari")
.replaceAll("February", "februari")
.replaceAll("March", "maart")
.replaceAll("April", "april")
.replaceAll("May", "mei")
.replaceAll("June", "juni")
.replaceAll("July", "juli")
.replaceAll("August", "augustus")
.replaceAll("September", "september")
.replaceAll("October", "oktober")
.replaceAll("November", "november")
.replaceAll("December", "december")
.replaceAll("Sell Out Risk: <u>HIGH</u>", "Uitverkooprisico: <u>HOOG</u>")
.replaceAll("Buy the official here", "Koop het officiële hier")
.replaceAll("RUSH MY ORDER NOW", "BESTEL NU")
.replaceAll("ORDER NOW", "BESTEL NU")
.replaceAll("BUY THE OFFICIAL NOW", "KOOP DE OFFICIËLE NU")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "KRIJG LAATSTE EENHEDEN MET KORTING")
.replaceAll("Hurry, you'll <u>lose</u> your discount in", "Schiet op, bent u uw korting <u>kwijt</u> binnen")
.replaceAll("Please, wait a few seconds for the page to load after clicking in the button", "Wacht alstublieft een paar seconden totdat de pagina is geladen nadat u op de knop hebt geklikt")
.replaceAll("Secure Payments", "Veilige Betalingen")
.replaceAll("24/7 Dedicated", "24/7 Toegewijde")
.replaceAll("Support", "Steun")
.replaceAll("<span style=\"color:#F19220;\">[GuaranteeDays]</span> Day Guarantee", "<span style=\"color:#F19220;\">[GuaranteeDays]</span> Dagen Garantie")
.replaceAll("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "Deze ongelooflijke formule van het [ProductName] brengt hoogwaardige grondstoffen samen, afkomstig uit verschillende delen van de wereld, die in synergie werken voor maximale prestaties.")
.replaceAll("Natural Formula", "Natuurlijke Formule")
.replaceAll("YOU’RE PROTECTED BY THE <span style=\"color: #F19220;\">[GuaranteeDays]-DAY MONEY BACK</span> GUARANTEE!", "U BENT BESCHERMD DOOR DE <span style=\"color: #F19220;\">[GuaranteeDays]-DAGEN GELD-TERUG-</span> GARANTIE!")
.replaceAll("The sellers are so confident with [ProductName] and services, that they back it with a <b>[GuaranteeDays] day money back guarantee</b>.", "De verkopers hebben zoveel vertrouwen in [ProductName] en de diensten dat ze het ondersteunen met een <b>geld-terug-garantie van [GuaranteeDays] dagen</b>.")
.replaceAll("If for any reason you are not fully satisfied with their products, simply return the purchased products in the original container within [GuaranteeDays] days of when you received your order.", "Als u om welke reden dan ook niet volledig tevreden bent met hun producten, kunt u de gekochte producten eenvoudigweg binnen [GuaranteeDays] dagen na ontvangst van uw bestelling in de originele verpakking retourneren.")
.replaceAll("They will refund you 100% of the purchase price, with absolutely no hassle.", "Ze betalen u 100% van de aankoopprijs terug, zonder enig gedoe.")
.replaceAll("BUY WITH GUARANTEE", "KOOP MET GARANTIE")
.replaceAll("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "Verzilver Hieronder uw <span style=\"color: #F19220;\">[ProductName]</span> met Korting Zolang de Voorraad Strekt")
.replaceAll("Terms", "Algemene Voorwaarden")
.replaceAll("Privacy", "Privacybeleid")
.replaceAll("Contact", "Contacteer ons")
.replaceAll("Shipping", "Verzend")
.replaceAll("Disclaimer", "Disclaimer")
.replaceAll("Order Now | All rights reserved", "Bestel Nu | Alle rechten voorbehouden")
} rep_Nld();
