function rep_Fin() {
document.body.innerHTML = document.body.innerHTML
.replaceAll("ATTENTION: Sale Ends Today", "HUOMIO: Alennusmyynti Päättyy Tänään")
.replaceAll("WARNING:</b></span> Due to extremely high media demand, there is limited supply of", "VAROITUS:</b></span> erittäin suuren mediakysynnän vuoksi")
.replaceAll("in stock as of", "on varastossa rajoitetusti alkaen")
.replaceAll("Sunday", "sunnuntai")
.replaceAll("Monday", "maanantai")
.replaceAll("Tuesday", "tiistai")
.replaceAll("Wednesday", "keskiviikko")
.replaceAll("Thursday", "torstai")
.replaceAll("Friday", "perjantai")
.replaceAll("Saturday", "lauantai")
.replaceAll("January", "tammikuu")
.replaceAll("February", "helmikuu")
.replaceAll("March", "maaliskuu")
.replaceAll("April", "huhtikuu")
.replaceAll("May", "toukokuu")
.replaceAll("June", "kesäkuu")
.replaceAll("July", "heinäkuu")
.replaceAll("August", "elokuu")
.replaceAll("September", "syyskuu")
.replaceAll("October", "lokakuu")
.replaceAll("November", "marraskuu")
.replaceAll("December", "joulukuu")
.replaceAll("Sell Out Risk: <u>HIGH</u>", "Ulosmyynnin Riski: <u>KORKEA</u>")
.replaceAll("Buy the official here", "Osta virallinen täältä")
.replaceAll("RUSH MY ORDER NOW", "TILAA NYT")
.replaceAll("ORDER NOW", "TILAA NYT")
.replaceAll("BUY THE OFFICIAL NOW", "OSTA VIRALLINEN TUOTE NYT")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "SAADA VIIMEISET YKSIKÖT ALENNUKSELLA")
.replaceAll("Hurry, you'll <u>lose</u> your discount in", "Pidä kiirettä, <u>menetät</u> alennuksesi")
.replaceAll("Please, wait a few seconds for the page to load after clicking in the button", "Ole kiltti, odota muutama sekunti sivun latautumista painikkeen painamisen jälkeen")
.replaceAll("Secure Payments", "Turvalliset Maksut")
.replaceAll("24/7 Dedicated", "24/7 Omistettu")
.replaceAll("Support", "Tuki")
.replaceAll("<span style=\"color:#F19220;\">[GuaranteeDays]</span> Day Guarantee", "<span style=\"color:#F19220;\">[GuaranteeDays]</span> Päivän Takuu")
.replaceAll("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "[ProductName] uskomaton koostumus yhdistää korkealaatuiset raaka-aineet, jotka on hankittu eri puolilta maailmaa ja jotka toimivat synergiassa maksimaalisen suorituskyvyn saavuttamiseksi.")
.replaceAll("Natural Formula", "Luonnollinen Kaava")
.replaceAll("YOU’RE PROTECTED BY THE <span style=\"color: #F19220;\">[GuaranteeDays]-DAY MONEY BACK</span> GUARANTEE!", "SINUA SUOJAA <span style=\"color: #F19220;\">[GuaranteeDays] PÄIVÄN RAHAT TAKAISIN</span> TAKUU!")
.replaceAll("The sellers are so confident with [ProductName] and services, that they back it with a <b>[GuaranteeDays] day money back guarantee</b>.", "Myyjät ovat niin luottavaisia [ProductName] ja palveluihin, että he tukevat sitä <b>[GuaranteeDays] päivän rahat takaisin -takuulla</b>.")
.replaceAll("If for any reason you are not fully satisfied with their products, simply return the purchased products in the original container within [GuaranteeDays] days of when you received your order.", "Jos et jostain syystä ole täysin tyytyväinen heidän tuotteisiinsa, palauta ostamasi tuotteet alkuperäisessä pakkauksessaan [GuaranteeDays] päivän kuluessa tilauksesi vastaanottamisesta.")
.replaceAll("They will refund you 100% of the purchase price, with absolutely no hassle.", "He palauttavat sinulle 100% ostohinnasta, ilman mitään vaivaa.")
.replaceAll("BUY WITH GUARANTEE", "OSTA TAKUULLA")
.replaceAll("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "Lunasta <span style=\"color: #F19220;\">[ProductName]</span> Alennuksella Niin Kauan Kuin Varastoa Riittää")
.replaceAll("MONEY BACK GUARANTEE !", "RAHAT TAKAISIN TAKUU !")
.replaceAll("Terms", "Yleiset Ehdot")
.replaceAll("Privacy", "Tietosuoja")
.replaceAll("Contact", "Yhteystiedot")
.replaceAll("Shipping", "Jälki")
.replaceAll("Disclaimer", "Vastuuvapauslauseke")
.replaceAll("Order Now | All rights reserved", "Tilaa Nyt | Kaikki oikeudet pidätetään")
} rep_Fin();
