var today = "den " + getNow.getDate() + ". " + getdayMonth[(getNow.getMonth())] + " " + thisYear + ".";
if (document.getElementById("today1") !== null) {document.getElementById("today1").innerHTML = today;}
document.body.innerHTML = document.body.innerHTML
.replace("Terms", "Betingelser")
.replace("Privacy", "Privatlivspolitik")
.replace("Contact", "Kontakt")
.replace("References", "Referencer")
.replace("Return", "Returpolitik")
.replace("Shipping", "Forsendelse")
.replace("Disclaimer", "Ansvarsfraskrivelse")
.replace("Report Spam", "Rapporter Spam")
.replace("Please, select your country below", "Vælg venligst dit land nedenfor")
.replace("If your country is not listed, click in the button below", "Hvis dit land ikke er på listen, skal du klikke på knappen nedenfor")
.replaceAll("PROCEED HERE", "FORTSÆT HER")
.replace("100% Satisfaction", "100% Tilfredshed")
.replace("[GuaDays]-Day Money Back Guarantee", "[GuaDays]-Dages Pengene-Tilbage-Garanti")
.replace("comes with a 100% money back guarantee", "kommer med en 100% pengene tilbage garanti")
.replace("full days from your original purchase. If you’re not totally and completely satisfied with their product or your results within the first [GuaDays] days simply let the vendors know by calling their toll-free number or dropping them an email and they’ll gladly give you a full refund within 48 hours of the product being returned. That’s right", "hele dage fra dit oprindelige køb. Hvis du ikke er helt og helt tilfreds med deres produkt eller dine resultater inden for de første [GuaDays] dage, skal du blot lade sælgerne vide det ved at ringe til deres gratisnummer eller sende dem en e-mail, og de vil med glæde give dig fuld refusion inden for 48 timer efter at produktet er returneret. Det er rigtigt")
.replace("simply return the product, even your empty bottles, anytime within [GuaDays] days of your purchase and you’ll receive a full, no-questions-asked refund (minus shipping and handling fees)", "du skal blot returnere produktet, selv dine tomme flasker, når som helst inden for [GuaDays] dage efter dit køb, og du vil modtage en fuld tilbagebetaling uden spørgsmål (minus forsendelses- og ekspeditionsgebyrer)")
.replace("Try <span", "Prøv <span")
.replace("Today!", "I dag!")
.replace("All Rights Reserved", "Alle rettigheder forbeholdes")
