function rep_Dnk() {
document.getElementById("today").innerHTML = getdayNames[(getNow.getDay())] + ", den " + getNow.getDate() + ". " + getdayMonth[(getNow.getMonth())];
document.body.innerHTML = document.body.innerHTML
.replace("ATTENTION: Sale Ends Today", "OPMÆRKSOMHED: Udsalget Slutter i Dag")
.replace("WARNING:</b></span> Due to extremely high media demand, there is limited supply of", "ADVARSEL:</b></span> På grund af ekstrem høj medieefterspørgsel er der begrænset udbud af")
.replace("in stock as of", "på lager fra den")
.replace("Sunday", "søndag")
.replace("Monday", "mandag")
.replace("Tuesday", "tirsdag")
.replace("Wednesday", "onsdag")
.replace("Thursday", "torsdag")
.replace("Friday", "fredag")
.replace("Saturday", "lørdag")
.replace("January", "januar")
.replace("February", "februar")
.replace("March", "marts")
.replace("April", "april")
.replace("May", "maj")
.replace("June", "juni")
.replace("July", "juli")
.replace("August", "august")
.replace("September", "september")
.replace("October", "oktober")
.replace("November", "november")
.replace("December", "december")
.replace("Up to [DiscountValue] Discount", "Op Til [DiscountValue] Rabat")
.replace("Sell Out Risk", "Udsalgsrisiko")
.replace("<u>HIGH</u>", "<u>HØJ</u>")
.replaceAll("Buy the official here", "Køb det officielle her")
.replaceAll("RUSH MY ORDER NOW", "BESTIL NU")
.replaceAll("ORDER NOW", "BESTIL NU")
.replaceAll("BUY THE OFFICIAL NOW", "KØB DET OFFICIELLE NU")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "FÅ SIDSTE ENHEDER MED RABAT NU")
.replace("Hurry, you'll <u>lose</u> your discount in", "Skynd dig, du <u>mister</u> din rabat på")
.replace("Please, wait a few seconds for the page to load after clicking in the button", "Vent venligst et par sekunder på, at siden indlæses, efter du har klikket på knappen")
.replace("Secure Payments", "Sikre Betalinger")
.replace("24/7 Dedicated", "24/7 Dedikeret")
.replace("Support", "Støtte")
.replace("<span style=\"color:#F19220;\">[GuaranteeDays]</span> Day Guarantee", "<span style=\"color:#F19220;\">[GuaranteeDays]</span> Dages Garanti")
.replace("Save Up To <span style=\"color:#F19220;\">[DiscountValue]", "Spar op Til <span style=\"color:#F19220;\">[DiscountValue]")
.replace("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "[ProductName] utrolige formel samler råvarer af høj kvalitet hentet fra forskellige dele af verden, som arbejder i synergi for maksimal ydeevne.")
.replace("Save Up To <span style=\"color: #F19220;\">[DiscountValue]</span> Buying Now!", "Spar op Til <span style=\"color: #F19220;\">[DiscountValue]</span> Ved at Købe Det Nu!")
.replace("Natural Formula", "Naturlig Formel")
.replace("YOU’RE PROTECTED BY THE <span style=\"color: #F19220;\">[GuaranteeDays]-DAY MONEY BACK</span> GUARANTEE!", "DU ER BESKYTTET AF <span style=\"color: #F19220;\">[GuaranteeDays] DAGES PENGE TILBAGE</span> GARANTI!")
.replace("The sellers are so confident with [ProductName] and services, that they back it with a <b>[GuaranteeDays] day money back guarantee</b>.", "Sælgerne er så sikre på [ProductName] og disse tjenester, at de bakker det op med en <b>[GuaranteeDays] dages pengene-tilbage-garanti</b>.")
.replace("If for any reason you are not fully satisfied with their products, simply return the purchased products in the original container within [GuaranteeDays] days of when you received your order.", "Hvis du af en eller anden grund ikke er fuldt ud tilfreds med deres produkter, skal du blot returnere de købte produkter i den originale beholder inden for [GuaranteeDays] dage efter, at du har modtaget din ordre.")
.replace("They will refund you 100% of the purchase price, with absolutely no hassle.", "De refunderer dig 100% af købsprisen, helt uden besvær.")
.replace("BUY WITH GUARANTEE", "KØB MED GARANTI")
.replace("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "Gør Krav på Dit Nedsatte <span style=\"color: #F19220;\">[ProductName]</span> Nedenfor, Så Længe Lager Haves")
.replace("MONEY BACK GUARANTEE !", "PENGE TILBAGE GARANTI !")
.replace("Prices indicated on the website are the average price per unit for the total number of units in each package", "Priserne angivet på hjemmesiden er gennemsnitsprisen pr. enhed for det samlede antal enheder i hver pakke")
.replaceAll("For the <b>", "For pakken med <b>")
.replaceAll("</span> Unit Pack", "</span> Enheder")
.replaceAll("you’ll pay", "betaler du")
.replaceAll("/unit</b>", "/enhed</b>")
.replaceAll("Total =", "Samlet =")
.replaceAll("instead of paying", "i stedet for at betale")
.replaceAll("you save <b>", "sparer du <b>")
.replaceAll("buying now", "ved at købe nu")
.replace("THE OFFICIAL", "DEN OFFICIELLE")
.replace("Terms", "Betingelser")
.replace("Privacy", "Privatlivspolitik")
.replace("Contact", "Kontakt")
.replace("Shipping", "Forsendelse")
.replace("Disclaimer", "Ansvarsfraskrivelse")
.replace("Order Now | All rights reserved", "Bestil Nu | Alle rettigheder forbeholdes")
} rep_Dnk();
