var today = getNow.getDate() + " " + getdayMonth[(getNow.getMonth())] + " " + thisYear + ".";
if (document.getElementById("today1") !== null) {document.getElementById("today1").innerHTML = today;}
document.body.innerHTML = document.body.innerHTML
.replace("Warning:</span></b> Limited supply for", "Avertissement:</span></b> Approvisionnement limité pour")
.replace("as of <b>", "au <b>")
.replace("Hurry!</b>", "Dépêchez-vous!</b>")
.replace("January", "janvier")
.replace("February", "février")
.replace("March", "mars")
.replace("April", "avril")
.replace("May", "mai")
.replace("June", "juin")
.replace("July", "juillet")
.replace("August", "août")
.replace("September", "septembre")
.replace("October", "octobre")
.replace("November", "novembre")
.replace("December", "décembre")
.replaceAll("RUSH ORDER NOW", "VÉRIFIER L'OFFRE")
.replaceAll("RUSH MY ORDER", "VÉRIFIER L'OFFRE")
.replaceAll("ORDER NOW", "COMMANDER")
.replace("<p>Try", "<p>Essaye")
.replace("Up to <b><u>[DiscValue]</u></b> OFF Today!", "Jusqu'à <b><u>[DiscValue]</u></b> OFF Aujourd'hui!")
.replace("Free Shipping on <b><u>Every Order!", "Livraison Gratuite <b><u>Chaque Achat!")
.replaceAll("Available to", "Disponible au")
.replaceAll("[Country] only", "[Country] seulement")
.replace("100% Satisfaction", "Satisfaction à 100%")
.replace("[GuaDays]-Day Money Back Guarantee", "Garantie Remboursement [GuaDays] Jours")
.replace("comes with a 100% money back guarantee", "est livré avec une garantie de remboursement à 100%")
.replace("full days from your original purchase. If you’re not totally and completely satisfied with their product or your results within the first [GuaDays] days simply let the vendors know by calling their toll-free number or dropping them an email and they’ll gladly give you a full refund within 48 hours of the product being returned. That’s right", "jours complets à compter de votre achat initial. Si vous n'êtes pas totalement et entièrement satisfait de leur produit ou de vos résultats dans les [GuaDays] premiers jours, informez-en simplement les fournisseurs en appelant leur numéro gratuit ou en leur envoyant un e-mail et ils se feront un plaisir de vous rembourser intégralement dans les 48 heures. du produit retourné. C'est vrai")
.replace("simply return the product, even your empty bottles, anytime within [GuaDays] days of your purchase and you’ll receive a full, no-questions-asked refund (minus shipping and handling fees)", "retournez simplement le produit, même vos bouteilles vides, à tout moment dans les [GuaDays] jours suivant votre achat et vous recevrez un remboursement complet, sans poser de questions (moins les frais d'expédition et de manutention)")
.replace("Inside every", "À l'intérieur de chaque")
.replace("you’ll find", "vous trouverez")
.replaceAll("Natural Formula", "Formule Naturelle")
.replaceAll("Easy to Use", "Facile à Utiliser")
.replaceAll("Non-GMO", "Non GMO")
.replaceAll("No Stimulants", "Pas de Stimulants")
.replaceAll("Non-Habit Forming", "Ne Crée pas d'habitude")
.replaceAll("Gluten Free", "Sans Gluten")
.replace("Order <b>[MaxUnits] Bottles</b> or <b>[MidUnits] Bottles</b> and Get <b><u>2 FREE Bonuses", "Commandez <b>[MaxUnits] bouteilles</b> ou <b>[MidUnits] bouteilles</b> et obtenez <b><u>2 Bonus GRATUITS")
.replace("Every Order Comes With", "Chaque Commande Comprend Également la")
.replace("FREE Shipping</u> Too", "Livraison GRATUITE</u>")
.replace("97% Of Customers Order [MaxUnits] Bottles (The Recommended Option)", "97% des Clients Commandent [MaxUnits] Bouteilles (L'option Recommandée)")
.replace("Real […] Users", "De Vraies Personnes de […]")
.replace("Real Life-Changing Results", "De Vrais Résultats")
.replaceAll("Verified Purchase", "Achat Vérifié")
.replace("Frequently Asked Questions", "Questions Fréquemment Posées")
.replace("Claim Your Discounted […] Below While Stocks Last", "Réclamez votre […] à Prix Réduit ci-Dessous Jusqu'à Épuisement des Stocks")
.replace("Customers say", "Les clients disent")
.replace("based on", "basé sur")
.replace("reviews!", "avis!")
.replace("Scientific References", "Références Scientifiques")
.replace("Please note that the information we provide is not intended to replace consultation with a qualified medical professional. We encourage you to inform your physician of changes you make to your lifestyle and discuss these with him or her. For questions or concerns about any medical conditions you may have, please contact your doctor.", "Veuillez noter que les informations que nous fournissons ne visent pas à remplacer la consultation d’un professionnel de la santé qualifié. Nous vous encourageons à informer votre médecin des changements que vous apportez à votre mode de vie et à en discuter avec lui. Pour toute question ou préoccupation concernant tout problème de santé que vous pourriez avoir, veuillez contacter votre médecin.")
.replace("Statements on this website have not been evaluated by the Food and Drug Administration. Products are not intended to diagnose, treat, cure or prevent any disease. If you are pregnant, nursing, taking medication, or have a medical condition, consult your physician before using these products.", "Les déclarations sur ce site Web n'ont pas été évaluées par la Food and Drug Administration. Les produits ne sont pas destinés à diagnostiquer, traiter, guérir ou prévenir une maladie. Si vous êtes enceinte, allaitez, prenez des médicaments ou souffrez d'un problème de santé, consultez votre médecin avant d'utiliser ces produits.")
.replace("Results in description and testimonials may not be typical results and individual results may vary.", "Les résultats dans la description et les témoignages peuvent ne pas être des résultats typiques et les résultats individuels peuvent varier.")
.replace("Terms", "Conditions")
.replace("Privacy", "Confidentialité")
.replace("Contact", "Contact")
.replace("References", "Références")
.replace("Return", "Retour")
.replaceAll("Shipping", "Expédition")
.replace("Disclaimer", "Avis de non-responsabilité")
.replace("Report Spam", "Signaler un Spam")
.replace("Order Now. All Rights Reserved.", "Commandez maintenant. Tous droits réservés.")
.replace("Claim Your Discounted […] By Clicking on the Button Below", "Réclamez Votre […] à Prix Réduit en Cliquant sur le Bouton ci-Dessous")
.replaceAll("ACCESS OFFICIAL WEBSITE", "ACCÉDER AU SITE OFFICIEL")
.replace("Special <b><u>Discount Code</u></b> Activated", "<b><u>Code de Réduction</u></b> Spécial Activé")
.replace("Save Up to <b><u>[DiscValue]</u></b> Today", "Économisez Jusqu'à <b><u>[DiscValue]</u></b> Aujourd'hui")
.replace("From Only <b><u>[Lower]</u></b> /Bottle", "À Partir de Seulement <b><u>[Lower]</u></b> /Bouteille")
.replace("Free Shipping on <b><u>Every Order!</u></b>", "Livraison Gratuite sur <b><u>Chaque Commande!</u></b>")
.replace("<b><u>[GuaDays] Day</u></b> Satisfaction Guarantee!", "Garantie de Satisfaction <b><u>[GuaDays] Jours!</u></b>")
.replace("Please, select your country below", "Veuillez sélectionner votre pays ci-dessous")
.replace("If your country is not listed, click in the button below", "Si votre pays n'est pas répertorié, cliquez sur le bouton ci-dessous")
.replaceAll("PROCEED HERE", "PROCÉDER ICI")
.replace("Today!", "Aujourd'hui!")
.replace("All Rights Reserved", "Tous droits réservés")
