function rep_Fren() {
document.getElementById("today").innerHTML = getdayNames[(getNow.getDay())] + ", " + getNow.getDate() + " " + getdayMonth[(getNow.getMonth())];
document.body.innerHTML = document.body.innerHTML
.replace("ATTENTION: Sale Ends Today", "ATTENTION: Vente se Termine Aujourd'hui")
.replace("WARNING:</b></span> Due to extremely high media demand, there is limited supply of", "AVERTISSEMENT:</b></span> En raison de la très forte demande des médias, il y a un approvisionnement limité des ")
.replace("in stock as of", "depuis le")
.replace("Sunday", "dimanche")
.replace("Monday", "lundi")
.replace("Tuesday", "mardi")
.replace("Wednesday", "mercredi")
.replace("Thursday", "jeudi")
.replace("Friday", "vendredi")
.replace("Saturday", "samedi")
.replace("January", "janvier")
.replace("February", "février")
.replace("March", "mars")
.replace("April", "avril")
.replace("May", "mai")
.replace("June", "juin")
.replace("July", "juillet")
.replace("August", "août")
.replace("September", "septembre")
.replace("October", "octobre")
.replace("November", "novembre")
.replace("December", "décembre")
.replace("Up to [DiscountValue] Discount", "Jusqu'à [DiscountValue] de Réduction")
.replace("Sell Out Risk", "Risque de Liquidation")
.replace("<u>HIGH</u>", "<u>ÉLEVÉ</u>")
.replaceAll("Buy the official here", "Achetez l'officiel ici")
.replaceAll("RUSH MY ORDER NOW", "DÉPÊCHEZ MA COMMANDE")
.replaceAll("ORDER NOW", "COMMANDER")
.replaceAll("BUY THE OFFICIAL NOW", "ACHETEZ L'OFFICIEL MAINTENANT")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "OBTENEZ LES DERNIÈRES UNITÉS ICI")
.replace("Hurry, you'll <u>lose</u> your discount in", "Dépêchez-vous, vous <u>perdrez</u> votre réduction dans")
.replace("Please, wait a few seconds for the page to load after clicking in the button", "Veuillez attendre quelques secondes que la page se charge après avoir cliqué sur le bouton")
.replace("Secure Payments", "Paiements Sécurisés")
.replace("24/7 Dedicated", "24/7 Dédié")
.replace("Support", "Support")
.replace("<span style=\"color:#F19220;\">[GuaranteeDays]</span> Day Guarantee", "<span style=\"color:#F19220;\">Garantie de</span> [GuaranteeDays] Jours")
.replace("Save Up To <span style=\"color:#F19220;\">[DiscountValue]", "Économisez Jusqu'à <span style=\"color:#F19220;\">[DiscountValue]")
.replace("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "La formule incroyable de [ProductName] rassemble des ingrédients bruts de haute qualité provenant de différentes parties du monde qui travaillent en synergie pour une performance maximale.")
.replace("Save Up To <span style=\"color: #F19220;\">[DiscountValue]</span> Buying Now!", "Économisez Jusqu'à <span style=\"color: #F19220;\">[DiscountValue]</span> en Achetant Maintenant!")
.replace("Natural Formula", "Formule Naturelle")
.replace("YOU’RE PROTECTED BY THE <span style=\"color: #F19220;\">[GuaranteeDays]-DAY MONEY BACK</span> GUARANTEE!", "VOUS ÊTES PROTÉGÉ PAR LA <span style=\"color: #F19220;\">GARANTIE DE [GuaranteeDays] JOURS</span>!")
.replace("The sellers are so confident with [ProductName] and services, that they back it with a <b>[GuaranteeDays] day money back guarantee</b>.", "Les vendeurs sont tellement confiants dans [ProductName] et ces services qu'ils le soutiennent avec une <b>garantie de [GuaranteeDays] jours</b>.")
.replace("If for any reason you are not fully satisfied with their products, simply return the purchased products in the original container within [GuaranteeDays] days of when you received your order.", "Si, pour une raison quelconque, vous n'êtes pas entièrement satisfait de leurs produits, retournez simplement les produits achetés dans leur emballage d'origine dans les [GuaranteeDays] jours suivant la réception de votre commande.")
.replace("They will refund you 100% of the purchase price, with absolutely no hassle.", "Ils vous rembourseront 100% du prix d'achat, sans aucun problème.")
.replace("BUY WITH GUARANTEE", "ACHETER AVEC GARANTIE")
.replace("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "Réclamez Votre <span style=\"color: #F19220;\">[ProductName]</span> à Prix Réduit ci-Dessous Jusqu'à Épuisement des Stocks")
.replace("MONEY BACK GUARANTEE !", "GARANTIE DE REMBOURSEMENT !")
.replace("Prices indicated on the website are the average price per unit for the total number of units in each package", "es prix indiqués sur le site internet sont le prix moyen unitaire pour le nombre total d'unités dans chaque forfait")
.replace("For the <b>", "Pour le Pack de <b>")
.replace("</span> Unit Pack", "</span> Unités")
.replace("you’ll pay", "vous paierez")
.replace("/unit</b>", "/unité</b>")
.replace("instead of paying", "au lieu de payer")
.replace("you save <b>", "vous économisez <b>")
.replace("buying now", "en achetant maintenant")
.replace("THE OFFICIAL", "L'OFFICIEL")
.replace("Terms", "Conditions")
.replace("Privacy", "Confidentialité")
.replace("Contact", "Contact")
.replace("Shipping", "Expédition")
.replace("Disclaimer", "Avis de non-responsabilité")
.replace("Order Now | All rights reserved", "Acheter Maintenant | Tous droits réservés")
} rep_Fren();
