function rep_Fre() {
document.body.innerHTML = document.body.innerHTML
.replaceAll("ATTENTION: Sale Ends Today", "ATTENTION: Vente se Termine Aujourd'hui")
.replaceAll("WARNING:</b></span> Due to extremely high media demand, there is limited supply of", "AVERTISSEMENT:</b></span> En raison de la demande extrêmement élevée des médias, l'offre de")
.replaceAll("in stock as of","en stock est limitée au")
.replaceAll("Sunday", "dimanche")
.replaceAll("Monday", "lundi")
.replaceAll("Tuesday", "mardi")
.replaceAll("Wednesday", "mercredi")
.replaceAll("Thursday", "jeudi")
.replaceAll("Friday", "vendredi")
.replaceAll("Saturday", "samedi")
.replaceAll("January", "janvier")
.replaceAll("February", "février")
.replaceAll("March", "mars")
.replaceAll("April", "avril")
.replaceAll("May", "mai")
.replaceAll("June", "juin")
.replaceAll("July", "juillet")
.replaceAll("August", "août")
.replaceAll("September", "septembre")
.replaceAll("October", "octobre")
.replaceAll("November", "novembre")
.replaceAll("December", "décembre")
.replaceAll("Sell Out Risk: <u>HIGH</u>", "Risque de Liquidation: <u>ÉLEVÉ</u>")
.replaceAll("Buy the official here", "Achetez le officiel ici")
.replaceAll("RUSH MY ORDER NOW", "DÉPÊCHEZ MA COMMANDE")
.replaceAll("ORDER NOW", "COMMANDER")
.replaceAll("BUY THE OFFICIAL NOW", "ACHETEZ LE OFFICIEL MAINTENANT")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "OBTENEZ LES DERNIÈRES UNITÉS ICI")
.replaceAll("Hurry, you'll <u>lose</u> your discount in", "Dépêchez-vous, vous <u>perdrez</u> votre réduction dans")
.replaceAll("Please, wait a few seconds for the page to load after clicking in the button", "Veuillez attendre quelques secondes que la page se charge après avoir cliqué sur le bouton")
.replaceAll("Secure Payments", "Paiements Sécurisés")
.replaceAll("24/7 Dedicated", "24/7 Dédié")
.replaceAll("Support", "Support")
.replaceAll("<span style=\"color:#F19220;\">[GuaranteeDays]</span> Day Guarantee", "<span style=\"color:#F19220;\">Garantie de</span> [GuaranteeDays] Jours")
.replaceAll("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "La formule incroyable de [ProductName] rassemble des ingrédients bruts de haute qualité provenant de différentes parties du monde qui travaillent en synergie pour une performance maximale.")
.replaceAll("Natural Formula", "Formule Naturelle")
.replaceAll("YOU’RE PROTECTED BY THE <span style=\"color: #F19220;\">[GuaranteeDays]-DAY MONEY BACK</span> GUARANTEE!", "VOUS ÊTES PROTÉGÉ PAR LA <span style=\"color: #F19220;\">GARANTIE DE [GuaranteeDays] JOURS</span>!")
.replaceAll("The sellers are so confident with [ProductName] and services, that they back it with a <b>[GuaranteeDays] day money back guarantee</b>.", "Les vendeurs sont tellement confiants dans [ProductName] et ces services qu'ils le soutiennent avec une <b>garantie de [GuaranteeDays] jours</b>.")
.replaceAll("If for any reason you are not fully satisfied with their products, simply return the purchased products in the original container within [GuaranteeDays] days of when you received your order.", "Si, pour une raison quelconque, vous n'êtes pas entièrement satisfait de leurs produits, retournez simplement les produits achetés dans leur emballage d'origine dans les [GuaranteeDays] jours suivant la réception de votre commande.")
.replaceAll("They will refund you 100% of the purchase price, with absolutely no hassle.", "Ils vous rembourseront 100% du prix d'achat, sans aucun problème.")
.replaceAll("BUY WITH GUARANTEE", "ACHETER AVEC GARANTIE")
.replaceAll("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "Réclamez Votre <span style=\"color: #F19220;\">[ProductName]</span> à Prix Réduit ci-Dessous Jusqu'à Épuisement des Stocks")
.replaceAll("Terms", "Conditions")
.replaceAll("Privacy", "Confidentialité")
.replaceAll("Contact", "Contact")
.replaceAll("Shipping", "Expédition")
.replaceAll("Disclaimer", "Avis de non-responsabilité")
.replaceAll("Order Now | All rights reserved", "Acheter Maintenant | Tous droits réservés")
} rep_Fre();
