function rep_Spa() {
document.getElementById("today").innerHTML = "el " +  getdayNames[(getNow.getDay())] + " " + getNow.getDate() + " de " + getdayMonth[(getNow.getMonth())];
document.body.innerHTML = document.body.innerHTML
.replace("ATTENTION: Sale Ends Today", "ATENCIÓN: La Venta Termina Hoy")
.replace("WARNING:</b></span> Due to extremely high media demand, there is limited supply of", "ADVERTENCIA:</b></span> Debido a la demanda extremadamente alta por los medios de comunicación, hay un suministro limitado de")
.replace("in stock as of", "en existencia (stock) a la fecha de")
.replace("Sunday", "domingo")
.replace("Monday", "lunes")
.replace("Tuesday", "martes")
.replace("Wednesday", "miércoles")
.replace("Thursday", "jueves")
.replace("Friday", "viernes")
.replace("Saturday", "sábado")
.replace("January", "enero")
.replace("February", "febrero")
.replace("March", "marzo")
.replace("April", "abril")
.replace("May", "mayo")
.replace("June", "junio")
.replace("July", "julio")
.replace("August", "agosto")
.replace("September", "septiembre")
.replace("October", "octubre")
.replace("November", "noviembre")
.replace("December", "diciembre")
.replace("Up to [DiscountValue] Discount", "Hasta [DiscountValue] de Descuento")
.replace("Sell Out Risk", "Riesgo de Agotarse")
.replace("<u>HIGH</u>", "<u>ALTO</u>")
.replaceAll("Buy the official here", "Compra el oficial aquí")
.replaceAll("RUSH MY ORDER NOW", "PEDIR AHORA")
.replaceAll("ORDER NOW", "PEDIR AHORA")
.replaceAll("BUY THE OFFICIAL NOW", "COMPRA EL OFICIAL AHORA")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "CONSIGUE LAS ÚLTIMAS UNIDADES")
.replace("Hurry, you'll <u>lose</u> your discount in", "Date prisa, <u>perderás</u> tu descuento en")
.replace("Please, wait a few seconds for the page to load after clicking in the button", "Por favor, espere unos segundos a que se cargue la página después de hacer clic en el botón")
.replace("Secure Payments", "Pagos Seguros")
.replace("24/7 Dedicated", "24/7 Dedicado")
.replaceAll("Support", "Soporte")
.replace("<span style=\"color:#F19220;\">[GuaranteeDays]</span> Day Guarantee", "<span style=\"color:#F19220;\">[GuaranteeDays]</span> Días de Garantía")
.replace("Save Up To <span style=\"color:#F19220;\">[DiscountValue]", "Ahorra Hasta <span style=\"color:#F19220;\">[DiscountValue]")
.replace("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "[ProductName] increíble fórmula reúne ingredientes crudos de alta calidad provenientes de diferentes partes del mundo que trabajan en sinergia para lograr el máximo rendimiento.")
.replace("Save Up To <span style=\"color: #F19220;\">[DiscountValue]</span> Buying Now!", "Ahorra Hasta <span style=\"color: #F19220;\">[DiscountValue]</span> Comprando Ahora!")
.replace("Natural Formula", "Fórmula Natural")
.replace("YOU’RE PROTECTED BY THE <span style=\"color: #F19220;\">[GuaranteeDays]-DAY MONEY BACK</span> GUARANTEE!", "ESTÁS PROTEGIDO POR LA <span style=\"color: #F19220;\">GARANTÍA DE [GuaranteeDays] DÍAS</span>")
.replace("The sellers are so confident with [ProductName] and services, that they back it with a <b>[GuaranteeDays] day money back guarantee</b>.", "Los vendedores tienen tanta confianza en [ProductName] y en sus servicios, que los respaldan con <b>[GuaranteeDays] días de garantía de devolución de dinero</b>.")
.replace("If for any reason you are not fully satisfied with their products, simply return the purchased products in the original container within [GuaranteeDays] days of when you received your order.", "Si por alguna razón no está completamente satisfecho con sus productos, simplemente devuelva los productos comprados en el contenedor original dentro de los [GuaranteeDays] días posteriores a la recepción de tu pedido.")
.replace("They will refund you 100% of the purchase price, with absolutely no hassle.", "Te reembolsarán el 100% del precio de compra, sin ningún problema.")
.replace("BUY WITH GUARANTEE", "COMPRA CON GARANTÍA")
.replace("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "Reclama <span style=\"color: #F19220;\">[ProductName]</span> con Descuento Abajo Hasta Agotar Suministros")
.replace("MONEY BACK GUARANTEE !", "GARANTÍA DE REEMBOLSO !")
.replace("Prices indicated on the website are the average price per unit for the total number of units in each package", "Los precios indicados en la web son el precio medio por unidad para el número total de unidades de cada paquete")
.replaceAll("For the <b>", "Por el Pack de <b>")
.replaceAll("</span> Unit Pack", "</span> Unidades")
.replaceAll("you’ll pay", "pagarás")
.replaceAll("/unit</b>", "/unidad</b>")
.replaceAll("instead of paying", "en vez de pagar")
.replaceAll("you save <b>", "tu ahorras <b>")
.replaceAll("buying now", "comprando ahora")
.replace("THE OFFICIAL", "EL OFICIAL")
.replace("Terms", "Términos")
.replace("Privacy", "Privacidad")
.replace("Contact", "Contacto")
.replace("Shipping", "Envío")
.replace("Disclaimer", "Descargo de responsabilidad")
.replace("Order Now | All rights reserved", "Compra Ahora | Todos los derechos reservados")
} rep_Spa();
