function rep_Spa() {
document.body.innerHTML = document.body.innerHTML
.replaceAll("ATTENTION: Sale Ends Today", "ATENCIÓN: La Venta Termina Hoy")
.replaceAll("WARNING:</b></span> Due to extremely high media demand, there is limited supply of", "ADVERTENCIA:</b></span> Debido a la demanda extremadamente alta por los medios de comunicación, hay un suministro limitado de")
.replaceAll("in stock as of", "en existencia (stock) a la fecha de")
.replaceAll("Sunday", "domingo")
.replaceAll("Monday", "lunes")
.replaceAll("Tuesday", "martes")
.replaceAll("Wednesday", "miércoles")
.replaceAll("Thursday", "jueves")
.replaceAll("Friday", "viernes")
.replaceAll("Saturday", "sábado")
.replaceAll("January", "enero")
.replaceAll("February", "febrero")
.replaceAll("March", "marzo")
.replaceAll("April", "abril")
.replaceAll("May", "mayo")
.replaceAll("June", "junio")
.replaceAll("July", "julio")
.replaceAll("August", "agosto")
.replaceAll("September", "septiembre")
.replaceAll("October", "octubre")
.replaceAll("November", "noviembre")
.replaceAll("December", "diciembre")
.replaceAll("Sell Out Risk: <u>HIGH</u>", "Riesgo de Agotarse: <u>ALTO</u>")
.replaceAll("Buy the official here", "Compra el oficial aquí")
.replaceAll("RUSH MY ORDER NOW", "PEDIR AHORA")
.replaceAll("ORDER NOW", "PEDIR AHORA")
.replaceAll("BUY THE OFFICIAL NOW", "COMPRA EL OFICIAL AHORA")
.replaceAll("GET LAST UNITS WITH DISCOUNT", "CONSIGUE LAS ÚLTIMAS UNIDADES")
.replaceAll("Hurry, you'll <u>lose</u> your discount in", "Date prisa, <u>perderás</u> tu descuento en")
.replaceAll("Please, wait a few seconds for the page to load after clicking in the button", "Por favor, espere unos segundos a que se cargue la página después de hacer clic en el botón")
.replaceAll("Secure Payments", "Pagos Seguros")
.replaceAll("24/7 Dedicated", "24/7 Dedicado")
.replaceAll("Support", "Soporte")
.replaceAll("[ProductName] incredible formula brings together high quality raw ingredients sourced from different parts of the world that work in synergy for maximum performance.", "[ProductName] increíble fórmula reúne ingredientes crudos de alta calidad provenientes de diferentes partes del mundo que trabajan en sinergia para lograr el máximo rendimiento.")
.replaceAll("Natural Formula", "Fórmula Natural")
.replaceAll("Claim Your Discounted <span style=\"color: #F19220;\">[ProductName]</span> Below While Stocks Last", "Reclama <span style=\"color: #F19220;\">[ProductName]</span> con Descuento Abajo Hasta Agotar Suministros")
.replaceAll("Terms", "Términos")
.replaceAll("Privacy", "Privacidad")
.replaceAll("Contact", "Contacto")
.replaceAll("Shipping", "Envío")
.replaceAll("Disclaimer", "Descargo de responsabilidad")
.replaceAll("Order Now | All rights reserved", "Compra Ahora | Todos los derechos reservados")
} rep_Spa();
